# Generated by Django 2.2 on 2020-05-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fullname',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='roll_no',
            new_name='roll_number',
        ),
    ]
