# Generated by Django 2.2 on 2020-05-28 06:28

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0002_auto_20200528_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
